Import icedtea-hotspot-insantiate-arrayallocator.patch patch from alpinelinux:
Workarounds build error:
Error: dl failure on line 895
Error relocating .../libjvm.so: _ZN14ArrayAllocatorImL10MemoryType7EE4freeEv: symbol not found

Possibly due to g++ 10.x error on not properly instantiating the template.

https://git.alpinelinux.org/aports/commit/?id=c4ee41d5047cded26ad472cb64f146f1e0e0c205